import { Rule, Severity } from '../../types.js';

export const cryptoRules: Rule[] = [
  {
    id: 'CRYPTO_MD5',
    category: 'Weak Cryptography',
    severity: Severity.High,
    message: 'MD5 is cryptographically broken — use SHA-256 or better',
    pattern: /(?:createHash|hashlib\.md5|MessageDigest\.getInstance)\s*\(\s*["']md5["']/i,
    cwe: 'CWE-328',
    owasp: 'A02:2021',
    fix: { description: 'Replace MD5 with SHA-256: createHash("sha256")' },
  },
  {
    id: 'CRYPTO_SHA1',
    category: 'Weak Cryptography',
    severity: Severity.Medium,
    message: 'SHA-1 is deprecated — use SHA-256 or better',
    pattern: /(?:createHash|hashlib\.sha1|MessageDigest\.getInstance)\s*\(\s*["']sha1["']/i,
    cwe: 'CWE-328',
    owasp: 'A02:2021',
    fix: { description: 'Replace SHA-1 with SHA-256' },
  },
  {
    id: 'CRYPTO_ECB_MODE',
    category: 'Weak Cryptography',
    severity: Severity.High,
    message: 'ECB mode preserves patterns — use CBC or GCM',
    pattern: /(?:ECB|MODE_ECB|AES\/ECB)/i,
    cwe: 'CWE-327',
    owasp: 'A02:2021',
    fix: { description: 'Use AES-GCM (authenticated encryption) instead of ECB' },
  },
  {
    id: 'CRYPTO_DES',
    category: 'Weak Cryptography',
    severity: Severity.High,
    message: 'DES/3DES is deprecated — use AES-256',
    pattern: /(?:^|[\s"'(,=])(?:DESede|TripleDES|3DES)(?:\/|\s|["')])/i,
    fileExtensions: ['.js', '.ts', '.jsx', '.tsx', '.py', '.java', '.go', '.rb', '.php', '.c', '.cpp', '.cs', '.rs'],
    cwe: 'CWE-327',
    owasp: 'A02:2021',
  },
  {
    id: 'CRYPTO_SMALL_KEY',
    category: 'Weak Cryptography',
    severity: Severity.High,
    message: 'RSA key size too small — use at least 2048 bits',
    pattern: /(?:generateKeyPair|KeyPairGenerator)\s*.*?(?:512|768|1024)\b/i,
    cwe: 'CWE-326',
    owasp: 'A02:2021',
    fix: { description: 'Use minimum 2048-bit RSA keys, or prefer Ed25519/ECDSA' },
  },
  {
    id: 'CRYPTO_HARDCODED_IV',
    category: 'Weak Cryptography',
    severity: Severity.High,
    message: 'Hardcoded initialization vector (IV) — use random IV per encryption',
    pattern: /(?:iv|IV|nonce)\s*[:=]\s*["'][A-Fa-f0-9]{16,}["']/i,
    cwe: 'CWE-329',
    owasp: 'A02:2021',
    fix: { description: 'Generate a random IV: crypto.randomBytes(16)' },
  },
  {
    id: 'CRYPTO_NO_PADDING',
    category: 'Weak Cryptography',
    severity: Severity.Medium,
    message: 'NoPadding cipher may leak plaintext length',
    pattern: /NoPadding/,
    cwe: 'CWE-327',
    owasp: 'A02:2021',
  },
  {
    id: 'CRYPTO_WEAK_RANDOM_JAVA',
    category: 'Weak Cryptography',
    severity: Severity.Medium,
    message: 'java.util.Random is not cryptographically secure — use SecureRandom',
    pattern: /new\s+Random\s*\(/,
    fileExtensions: ['.java'],
    cwe: 'CWE-338',
    owasp: 'A02:2021',
    fix: { description: 'Use java.security.SecureRandom instead' },
  },
];
