import { Rule, Severity } from '../../types.js';

export const dependencyRules: Rule[] = [
  {
    id: 'DEP_EVAL',
    category: 'Code Injection',
    severity: Severity.Critical,
    message: 'eval() usage — potential code injection vector',
    pattern: /\beval\s*\(/,
    fileExtensions: ['.ts', '.js', '.jsx', '.tsx', '.py'],
    cwe: 'CWE-95',
    owasp: 'A03:2021',
    fix: { description: 'Avoid eval(). Use JSON.parse() for data, or safe alternatives like vm2 sandbox.' },
  },
  {
    id: 'DEP_FUNCTION_CONSTRUCTOR',
    category: 'Code Injection',
    severity: Severity.Critical,
    message: 'Function constructor — equivalent to eval()',
    pattern: /new\s+Function\s*\(/,
    fileExtensions: ['.ts', '.js', '.jsx', '.tsx'],
    cwe: 'CWE-95',
    owasp: 'A03:2021',
  },
  {
    id: 'DEP_EXEC_UNSANITIZED',
    category: 'Command Injection',
    severity: Severity.Critical,
    message: 'exec/spawn with potential user input — use execFile with args array',
    pattern: /(?:child_process|exec|execSync|spawn|spawnSync)\s*\(\s*(?:`[^`]*\$\{|[^)]*\+\s*(?:req\.|params\.|query\.|body\.|input|user))/i,
    fileExtensions: ['.ts', '.js'],
    cwe: 'CWE-78',
    owasp: 'A03:2021',
    fix: { description: 'Use execFile() with an args array instead of exec() with string interpolation' },
  },
  {
    id: 'DEP_EXEC_SHELL',
    category: 'Command Injection',
    severity: Severity.High,
    message: 'Shell execution detected — ensure input is sanitized',
    pattern: /(?:exec|execSync|system|popen|subprocess\.call)\s*\(/,
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
  {
    id: 'DEP_DYNAMIC_REQUIRE',
    category: 'Code Injection',
    severity: Severity.High,
    message: 'Dynamic require/import with variable — potential code injection',
    pattern: /(?:require|import)\s*\(\s*(?!["'`])[a-zA-Z]/,
    fileExtensions: ['.ts', '.js'],
    cwe: 'CWE-95',
    owasp: 'A03:2021',
  },
  {
    id: 'DEP_DESERIALIZE',
    category: 'Insecure Deserialization',
    severity: Severity.High,
    message: 'Unsafe deserialization — validate and sanitize input',
    pattern: /(?:pickle\.loads|yaml\.load\s*\([^)]*(?!Loader)|unserialize|Marshal\.load|JSON\.parse\s*\(\s*(?:req\.|params\.|body\.))/i,
    cwe: 'CWE-502',
    owasp: 'A08:2021',
    fix: { description: 'Use safe loaders: yaml.safe_load(), validate JSON schema before parsing user input' },
  },
  {
    id: 'DEP_PATH_TRAVERSAL',
    category: 'Path Traversal',
    severity: Severity.High,
    message: 'Path constructed from user input — validate and normalize paths',
    pattern: /(?:readFile|writeFile|createReadStream|open|access)\s*\([^)]*(?:req\.|params\.|query\.|body\.)/i,
    fileExtensions: ['.ts', '.js'],
    cwe: 'CWE-22',
    owasp: 'A01:2021',
    fix: { description: 'Use path.resolve() and validate the resolved path starts with expected directory' },
  },
  {
    id: 'DEP_INSECURE_RANDOM',
    category: 'Weak Cryptography',
    severity: Severity.Medium,
    message: 'Math.random() for security context — use crypto.randomBytes()',
    pattern: /Math\.random\s*\(\)/,
    fileExtensions: ['.ts', '.js', '.jsx', '.tsx'],
    cwe: 'CWE-338',
    owasp: 'A02:2021',
    fix: { description: 'Use crypto.randomBytes() or crypto.randomUUID() for security-sensitive values' },
  },
  {
    id: 'DEP_HTTP_NO_TLS',
    category: 'Insecure Transport',
    severity: Severity.Medium,
    message: 'HTTP URL in code — use HTTPS instead',
    pattern: /["']http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0)/,
    cwe: 'CWE-319',
    owasp: 'A02:2021',
    fix: { description: 'Use HTTPS to encrypt data in transit' },
  },
  {
    id: 'DEP_SHELL_TRUE',
    category: 'Command Injection',
    severity: Severity.High,
    message: 'subprocess with shell=True — vulnerable to command injection',
    pattern: /subprocess\.(?:call|run|Popen)\s*\([^)]*shell\s*=\s*True/i,
    fileExtensions: ['.py'],
    cwe: 'CWE-78',
    owasp: 'A03:2021',
    fix: { description: 'Use shell=False (default) and pass args as a list' },
  },
  {
    id: 'DEP_OS_SYSTEM',
    category: 'Command Injection',
    severity: Severity.High,
    message: 'os.system() is vulnerable to injection — use subprocess with shell=False',
    pattern: /os\.system\s*\(/,
    fileExtensions: ['.py'],
    cwe: 'CWE-78',
    owasp: 'A03:2021',
  },
];
