import { Rule, Severity } from '../../types.js';

export const goRules: Rule[] = [
  {
    id: 'GO_UNSAFE_PTR',
    category: 'Unsafe Code',
    severity: Severity.High,
    message: 'unsafe.Pointer usage — may cause memory corruption',
    pattern: /unsafe\.Pointer/,
    fileExtensions: ['.go'],
    cwe: 'CWE-787',
    owasp: 'A06:2021',
  },
  {
    id: 'GO_ERR_IGNORED',
    category: 'Error Handling',
    severity: Severity.Medium,
    message: 'Error return value ignored — always check errors',
    pattern: /\b\w+\s*,\s*_\s*(?::=|=)\s*\w+\.\w+\s*\(/,
    fileExtensions: ['.go'],
    cwe: 'CWE-391',
    owasp: 'A04:2021',
    fix: { description: 'Handle the error: if err != nil { return err }' },
  },
  {
    id: 'GO_SQL_SPRINTF',
    category: 'SQL Injection',
    severity: Severity.Critical,
    message: 'fmt.Sprintf in SQL query — use parameterized queries',
    pattern: /(?:db\.(?:Query|Exec)|\.QueryRow)\s*\(\s*fmt\.Sprintf/,
    fileExtensions: ['.go'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    fix: { description: 'Use db.Query("SELECT * FROM x WHERE id = $1", id)' },
  },
  {
    id: 'GO_GOROUTINE_LEAK',
    category: 'Resource Leak',
    severity: Severity.Medium,
    message: 'Goroutine without context/done channel — may leak',
    pattern: /go\s+func\s*\(\s*\)\s*\{(?:(?!ctx|context|done|cancel).)*\}\s*\(\s*\)/,
    fileExtensions: ['.go'],
    cwe: 'CWE-404',
    owasp: 'A06:2021',
  },
  {
    id: 'GO_UNESCAPED_TEMPLATE',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'text/template instead of html/template — no auto-escaping',
    pattern: /["']text\/template["']/,
    fileExtensions: ['.go'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
    fix: { description: 'Use html/template for HTML output — it auto-escapes' },
  },
  {
    id: 'GO_DEFER_BODY_CLOSE',
    category: 'Resource Leak',
    severity: Severity.Low,
    message: 'HTTP response body not deferred for close — may leak connections',
    pattern: /http\.(?:Get|Post|Do)\s*\((?:(?!defer\s+.*\.Body\.Close).)*$/,
    fileExtensions: ['.go'],
    cwe: 'CWE-404',
    owasp: 'A06:2021',
  },
  {
    id: 'GO_WEAK_RAND',
    category: 'Weak Cryptography',
    severity: Severity.Medium,
    message: 'math/rand is not cryptographically secure — use crypto/rand',
    pattern: /["']math\/rand["']/,
    fileExtensions: ['.go'],
    cwe: 'CWE-338',
    owasp: 'A02:2021',
  },
  {
    id: 'GO_TLS_INSECURE',
    category: 'Authentication',
    severity: Severity.High,
    message: 'TLS InsecureSkipVerify — vulnerable to MITM',
    pattern: /InsecureSkipVerify\s*:\s*true/,
    fileExtensions: ['.go'],
    cwe: 'CWE-295',
    owasp: 'A07:2021',
  },
];
