import { Rule, Severity } from '../../types.js';

export const infoDisclosureRules: Rule[] = [
  {
    id: 'INFO_STACK_TRACE',
    category: 'Information Disclosure',
    severity: Severity.Medium,
    message: 'Stack trace sent in response — hide in production',
    pattern: /(?:err|error)\.stack\b.*(?:res\.|response\.|send|json|render)/i,
    cwe: 'CWE-209',
    owasp: 'A04:2021',
    fix: { description: 'Return generic error messages in production. Log stack traces server-side only.' },
  },
  {
    id: 'INFO_DEBUG_MODE',
    category: 'Information Disclosure',
    severity: Severity.Medium,
    message: 'Debug mode enabled — disable in production',
    pattern: /(?:DEBUG\s*[:=]\s*(?:true|1|["']true["'])|app\.debug\s*=\s*True|\.enableDebug|FLASK_DEBUG\s*=\s*1)/i,
    cwe: 'CWE-489',
    owasp: 'A05:2021',
    fix: { description: 'Disable debug mode in production: DEBUG=false' },
  },
  {
    id: 'INFO_VERSION_HEADER',
    category: 'Information Disclosure',
    severity: Severity.Low,
    message: 'Server version header exposed — remove to prevent fingerprinting',
    pattern: /(?:X-Powered-By|Server)\s*[:=]\s*["'][^"']+["']/i,
    cwe: 'CWE-200',
    owasp: 'A05:2021',
    fix: { description: 'Remove X-Powered-By header: app.disable("x-powered-by")' },
  },
  {
    id: 'INFO_VERBOSE_ERROR',
    category: 'Information Disclosure',
    severity: Severity.Medium,
    message: 'Detailed error message sent to client — use generic messages',
    pattern: /(?:res\.(?:send|json)\s*\(\s*(?:err|error)\b|catch.*res\..*(?:message|toString))/i,
    cwe: 'CWE-209',
    owasp: 'A04:2021',
  },
  {
    id: 'INFO_TODO_FIXME',
    category: 'Information Disclosure',
    severity: Severity.Info,
    message: 'TODO/FIXME/HACK/XXX comment — review before deployment',
    pattern: /\/\/\s*(?:TODO|FIXME|HACK|XXX|BUG)\b/i,
    cwe: 'CWE-546',
    owasp: 'A04:2021',
  },
  {
    id: 'INFO_CONSOLE_LOG',
    category: 'Information Disclosure',
    severity: Severity.Low,
    message: 'console.log in production code — may leak sensitive data',
    pattern: /console\.log\s*\(\s*(?:.*(?:password|token|secret|key|auth|credential|session))/i,
    cwe: 'CWE-532',
    owasp: 'A09:2021',
  },
  {
    id: 'INFO_SOURCE_MAP',
    category: 'Information Disclosure',
    severity: Severity.Low,
    message: 'Source map reference — may expose source code in production',
    pattern: /\/\/[#@]\s*sourceMappingURL\s*=/,
    fileExtensions: ['.js', '.css'],
    cwe: 'CWE-540',
    owasp: 'A05:2021',
  },
];
