import { Rule, Severity } from '../../types.js';

export const injectionRules: Rule[] = [
  {
    id: 'INJ_LDAP',
    category: 'LDAP Injection',
    severity: Severity.High,
    message: 'LDAP query with user input — sanitize special characters',
    pattern: /(?:ldap\.search|search_s|search_ext_s)\s*\([^)]*(?:req\.|params\.|body\.|input|user|\+\s*\w)/i,
    cwe: 'CWE-90',
    owasp: 'A03:2021',
  },
  {
    id: 'INJ_LOG',
    category: 'Log Injection',
    severity: Severity.Medium,
    message: 'User input in log statement — sanitize to prevent log forging',
    pattern: /(?:console\.log|logger\.\w+|log\.(?:info|warn|error|debug))\s*\([^)]*(?:req\.|params\.|body\.|query\.)/i,
    cwe: 'CWE-117',
    owasp: 'A09:2021',
    fix: { description: 'Sanitize user input before logging: strip newlines and control characters' },
  },
  {
    id: 'INJ_TEMPLATE',
    category: 'Template Injection',
    severity: Severity.Critical,
    message: 'Server-side template injection — never pass user input to template engine render',
    pattern: /(?:render_template_string|Template\s*\(|Jinja2|nunjucks\.renderString|ejs\.render)\s*\(\s*(?:req\.|params\.|body\.|input|user)/i,
    cwe: 'CWE-1336',
    owasp: 'A03:2021',
  },
  {
    id: 'INJ_XPATH',
    category: 'XPath Injection',
    severity: Severity.High,
    message: 'XPath query with string concatenation — use parameterized XPath',
    pattern: /(?:xpath|evaluate|selectNodes)\s*\([^)]*(?:\+\s*(?:req\.|params\.|body\.)|`[^`]*\$\{)/i,
    cwe: 'CWE-643',
    owasp: 'A03:2021',
  },
  {
    id: 'INJ_NOSQL',
    category: 'NoSQL Injection',
    severity: Severity.High,
    message: 'NoSQL query with unsanitized input — validate and sanitize',
    pattern: /\.\s*(?:find|findOne|findOneAndUpdate|updateOne|deleteOne)\s*\(\s*(?:req\.|params\.|body\.)/i,
    fileExtensions: ['.ts', '.js'],
    cwe: 'CWE-943',
    owasp: 'A03:2021',
    fix: { description: 'Validate input types and use mongo-sanitize to strip $ operators' },
  },
  {
    id: 'INJ_REGEX_USER',
    category: 'Regex Injection',
    severity: Severity.High,
    message: 'User input in RegExp constructor — escape special characters',
    pattern: /new\s+RegExp\s*\(\s*(?:req\.|params\.|body\.|query\.|input|user)/i,
    fileExtensions: ['.ts', '.js'],
    cwe: 'CWE-1333',
    owasp: 'A03:2021',
    fix: { description: 'Escape user input before using in RegExp, or use a safe regex library' },
  },
  {
    id: 'INJ_HEADER',
    category: 'Header Injection',
    severity: Severity.High,
    message: 'User input in HTTP header — validate to prevent CRLF injection',
    pattern: /(?:setHeader|writeHead|set)\s*\([^)]*(?:req\.|params\.|body\.|query\.)/i,
    fileExtensions: ['.ts', '.js'],
    cwe: 'CWE-113',
    owasp: 'A03:2021',
  },
];
