import { Rule, Severity } from '../../types.js';

export const javaRules: Rule[] = [
  {
    id: 'JAVA_RUNTIME_EXEC',
    category: 'Command Injection',
    severity: Severity.Critical,
    message: 'Runtime.exec() with string — use ProcessBuilder with args list',
    pattern: /Runtime\.getRuntime\s*\(\s*\)\s*\.exec\s*\(\s*(?!new\s+String)/,
    fileExtensions: ['.java'],
    cwe: 'CWE-78',
    owasp: 'A03:2021',
    fix: { description: 'Use ProcessBuilder with separate command and arguments' },
  },
  {
    id: 'JAVA_DESERIALIZATION',
    category: 'Insecure Deserialization',
    severity: Severity.Critical,
    message: 'ObjectInputStream.readObject() — may lead to RCE',
    pattern: /(?:ObjectInputStream|readObject|readUnshared)\s*\(/,
    fileExtensions: ['.java'],
    cwe: 'CWE-502',
    owasp: 'A08:2021',
    fix: { description: 'Use a serialization filter (ObjectInputFilter) or alternative like JSON' },
  },
  {
    id: 'JAVA_WEAK_CRYPTO',
    category: 'Weak Cryptography',
    severity: Severity.High,
    message: 'Weak cipher algorithm — use AES with GCM mode',
    pattern: /Cipher\.getInstance\s*\(\s*["'](?:DES|RC4|RC2|Blowfish|DESede)/i,
    fileExtensions: ['.java'],
    cwe: 'CWE-327',
    owasp: 'A02:2021',
  },
  {
    id: 'JAVA_SQL_STATEMENT',
    category: 'SQL Injection',
    severity: Severity.Critical,
    message: 'Statement instead of PreparedStatement — use parameterized queries',
    pattern: /(?:createStatement|Statement\s+\w+\s*=).*(?:executeQuery|executeUpdate)\s*\(\s*(?!["'])/,
    fileExtensions: ['.java'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
  },
  {
    id: 'JAVA_XXE_PARSER',
    category: 'XML External Entity',
    severity: Severity.High,
    message: 'XML parser without XXE protection — set FEATURE_SECURE_PROCESSING',
    pattern: /(?:DocumentBuilderFactory|SAXParserFactory|XMLInputFactory)\.new(?:Instance|Factory)\s*\(\s*\)/,
    fileExtensions: ['.java'],
    cwe: 'CWE-611',
    owasp: 'A05:2021',
  },
  {
    id: 'JAVA_EMPTY_CATCH',
    category: 'Error Handling',
    severity: Severity.Medium,
    message: 'Empty catch block — exceptions silently swallowed',
    pattern: /catch\s*\([^)]+\)\s*\{\s*\}/,
    fileExtensions: ['.java'],
    cwe: 'CWE-390',
    owasp: 'A04:2021',
  },
  {
    id: 'JAVA_HARDCODED_KEY',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Hardcoded cryptographic key in source',
    pattern: /SecretKeySpec\s*\(\s*["'][^"']+["']\.getBytes/,
    fileExtensions: ['.java'],
    cwe: 'CWE-321',
    owasp: 'A02:2021',
  },
  {
    id: 'JAVA_TRUST_ALL_CERTS',
    category: 'Authentication',
    severity: Severity.Critical,
    message: 'TrustManager that trusts all certificates — vulnerable to MITM',
    pattern: /(?:X509TrustManager|TrustAllCerts|AcceptAllTrustManager|checkServerTrusted\s*\([^)]*\)\s*\{\s*\})/,
    fileExtensions: ['.java'],
    cwe: 'CWE-295',
    owasp: 'A07:2021',
  },
];
