import { Rule, Severity } from '../../types.js';

export const phpRules: Rule[] = [
  {
    id: 'PHP_INCLUDE_VAR',
    category: 'File Inclusion',
    severity: Severity.Critical,
    message: 'include/require with variable — Local/Remote File Inclusion',
    pattern: /(?:include|require|include_once|require_once)\s*\(\s*\$(?:_GET|_POST|_REQUEST|\w+)/i,
    fileExtensions: ['.php'],
    cwe: 'CWE-98',
    owasp: 'A03:2021',
    fix: { description: 'Use a whitelist of allowed include paths instead of user input' },
  },
  {
    id: 'PHP_SUPERGLOBAL_DIRECT',
    category: 'Input Validation',
    severity: Severity.High,
    message: 'Direct use of $_GET/$_POST/$_REQUEST — sanitize and validate',
    pattern: /\$_(?:GET|POST|REQUEST)\s*\[/,
    fileExtensions: ['.php'],
    cwe: 'CWE-20',
    owasp: 'A03:2021',
    fix: { description: 'Use filter_input() or validate input before use' },
  },
  {
    id: 'PHP_PREG_E',
    category: 'Code Injection',
    severity: Severity.Critical,
    message: 'preg_replace with /e modifier — allows code execution',
    pattern: /preg_replace\s*\(\s*["']\/[^"']*\/e["']/,
    fileExtensions: ['.php'],
    cwe: 'CWE-95',
    owasp: 'A03:2021',
    fix: { description: 'Use preg_replace_callback() instead of /e modifier' },
  },
  {
    id: 'PHP_ASSERT',
    category: 'Code Injection',
    severity: Severity.Critical,
    message: 'assert() with string argument — equivalent to eval()',
    pattern: /assert\s*\(\s*\$/,
    fileExtensions: ['.php'],
    cwe: 'CWE-95',
    owasp: 'A03:2021',
  },
  {
    id: 'PHP_EXTRACT',
    category: 'Mass Assignment',
    severity: Severity.High,
    message: 'extract() on user data — creates variables from attacker-controlled input',
    pattern: /extract\s*\(\s*\$_(?:GET|POST|REQUEST)/,
    fileExtensions: ['.php'],
    cwe: 'CWE-915',
    owasp: 'A04:2021',
  },
  {
    id: 'PHP_ECHO_UNESCAPED',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'echo/print with unescaped user input — use htmlspecialchars()',
    pattern: /(?:echo|print)\s+\$_(?:GET|POST|REQUEST)/,
    fileExtensions: ['.php'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
    fix: { description: 'Use htmlspecialchars($var, ENT_QUOTES, "UTF-8")' },
  },
  {
    id: 'PHP_SERIALIZE',
    category: 'Insecure Deserialization',
    severity: Severity.High,
    message: 'unserialize() on user data — may lead to RCE',
    pattern: /unserialize\s*\(\s*\$_(?:GET|POST|REQUEST|COOKIE)/,
    fileExtensions: ['.php'],
    cwe: 'CWE-502',
    owasp: 'A08:2021',
  },
  {
    id: 'PHP_MYSQL_DEPRECATED',
    category: 'SQL Injection',
    severity: Severity.High,
    message: 'mysql_* functions are deprecated and lack parameterized queries — use PDO',
    pattern: /mysql_(?:query|fetch|connect|real_escape_string)\s*\(/,
    fileExtensions: ['.php'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
  },
];
