import { Rule, Severity } from '../../types.js';

export const pythonRules: Rule[] = [
  {
    id: 'PY_PICKLE',
    category: 'Insecure Deserialization',
    severity: Severity.Critical,
    message: 'pickle.loads on untrusted data — may lead to RCE',
    pattern: /pickle\.(?:loads?|Unpickler)\s*\(/,
    fileExtensions: ['.py'],
    cwe: 'CWE-502',
    owasp: 'A08:2021',
    fix: { description: 'Use JSON or a safe serialization format. Never unpickle untrusted data.' },
  },
  {
    id: 'PY_YAML_LOAD',
    category: 'Insecure Deserialization',
    severity: Severity.Critical,
    message: 'yaml.load() without SafeLoader — may execute arbitrary code',
    pattern: /yaml\.load\s*\([^)]*(?!Loader|SafeLoader|BaseLoader)\)/,
    fileExtensions: ['.py'],
    cwe: 'CWE-502',
    owasp: 'A08:2021',
    fix: { description: 'Use yaml.safe_load() or yaml.load(data, Loader=SafeLoader)' },
  },
  {
    id: 'PY_FLASK_DEBUG',
    category: 'Information Disclosure',
    severity: Severity.High,
    message: 'Flask debug mode — exposes interactive debugger with code execution',
    pattern: /app\.run\s*\([^)]*debug\s*=\s*True/,
    fileExtensions: ['.py'],
    cwe: 'CWE-489',
    owasp: 'A05:2021',
    fix: { description: 'Set debug=False in production' },
  },
  {
    id: 'PY_DJANGO_SECRET',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Hardcoded Django SECRET_KEY — use environment variable',
    pattern: /SECRET_KEY\s*=\s*["'][^"']{10,}["']/,
    fileExtensions: ['.py'],
    cwe: 'CWE-798',
    owasp: 'A07:2021',
    fix: { description: 'Use os.environ.get("SECRET_KEY") or django-environ' },
  },
  {
    id: 'PY_EXEC',
    category: 'Code Injection',
    severity: Severity.Critical,
    message: 'exec() with dynamic input — potential code injection',
    pattern: /\bexec\s*\(\s*(?!["'])/,
    fileExtensions: ['.py'],
    cwe: 'CWE-95',
    owasp: 'A03:2021',
  },
  {
    id: 'PY_COMPILE',
    category: 'Code Injection',
    severity: Severity.High,
    message: 'compile() + exec/eval — dynamic code execution',
    pattern: /compile\s*\([^)]+\)\s*.*(?:exec|eval)/,
    fileExtensions: ['.py'],
    cwe: 'CWE-95',
    owasp: 'A03:2021',
  },
  {
    id: 'PY_TEMPFILE_INSECURE',
    category: 'Race Condition',
    severity: Severity.Medium,
    message: 'tempfile.mktemp() is insecure — use tempfile.mkstemp()',
    pattern: /tempfile\.mktemp\s*\(/,
    fileExtensions: ['.py'],
    cwe: 'CWE-377',
    owasp: 'A06:2021',
    fix: { description: 'Use tempfile.mkstemp() or tempfile.NamedTemporaryFile()' },
  },
  {
    id: 'PY_DJANGO_RAW_SQL',
    category: 'SQL Injection',
    severity: Severity.High,
    message: 'Django raw SQL with format string — use params argument',
    pattern: /\.raw\s*\(\s*(?:f["']|["'].*?%s.*?["']\s*%|["'].*?\.format)/,
    fileExtensions: ['.py'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    fix: { description: 'Use Model.objects.raw("SELECT * FROM x WHERE id = %s", [user_id])' },
  },
  {
    id: 'PY_JINJA_AUTOESCAPE',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'Jinja2 with autoescape disabled — XSS risk',
    pattern: /Environment\s*\([^)]*autoescape\s*=\s*False/,
    fileExtensions: ['.py'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
    fix: { description: 'Set autoescape=True or use select_autoescape()' },
  },
  {
    id: 'PY_HASHLIB_WEAK',
    category: 'Weak Cryptography',
    severity: Severity.Medium,
    message: 'Weak hash for password/security — use bcrypt or argon2',
    pattern: /hashlib\.(?:md5|sha1)\s*\(/,
    fileExtensions: ['.py'],
    cwe: 'CWE-328',
    owasp: 'A02:2021',
  },
];
