import { Rule, Severity } from '../../types.js';

export const rustRules: Rule[] = [
  {
    id: 'RUST_UNSAFE',
    category: 'Unsafe Code',
    severity: Severity.High,
    message: 'unsafe block — review for memory safety violations',
    pattern: /\bunsafe\s*\{/,
    fileExtensions: ['.rs'],
    cwe: 'CWE-787',
    owasp: 'A06:2021',
  },
  {
    id: 'RUST_UNWRAP',
    category: 'Error Handling',
    severity: Severity.Medium,
    message: '.unwrap() will panic on error — use ? operator or match',
    pattern: /\.unwrap\s*\(\s*\)/,
    fileExtensions: ['.rs'],
    cwe: 'CWE-248',
    owasp: 'A06:2021',
    fix: { description: 'Use .unwrap_or_default(), .expect("reason"), or the ? operator' },
  },
  {
    id: 'RUST_EXPECT',
    category: 'Error Handling',
    severity: Severity.Low,
    message: '.expect() will panic — prefer proper error handling in libraries',
    pattern: /\.expect\s*\(\s*["']/,
    fileExtensions: ['.rs'],
    cwe: 'CWE-248',
    owasp: 'A06:2021',
  },
  {
    id: 'RUST_TRANSMUTE',
    category: 'Unsafe Code',
    severity: Severity.Critical,
    message: 'std::mem::transmute — extremely dangerous, may cause UB',
    pattern: /(?:mem::transmute|transmute_copy)\s*[:<(]/,
    fileExtensions: ['.rs'],
    cwe: 'CWE-704',
    owasp: 'A06:2021',
  },
  {
    id: 'RUST_FORMAT_SQL',
    category: 'SQL Injection',
    severity: Severity.Critical,
    message: 'format! in SQL query — use parameterized queries',
    pattern: /(?:execute|query)\s*\(\s*&?\s*format!\s*\(\s*["'](?:SELECT|INSERT|UPDATE|DELETE)/i,
    fileExtensions: ['.rs'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
  },
  {
    id: 'RUST_RAW_PTR',
    category: 'Unsafe Code',
    severity: Severity.High,
    message: 'Raw pointer dereference — may cause use-after-free or null deref',
    pattern: /\*(?:mut|const)\s+\w+/,
    fileExtensions: ['.rs'],
    cwe: 'CWE-476',
    owasp: 'A06:2021',
  },
];
