import { Rule, Severity } from '../../types.js';

export const secretRules: Rule[] = [
  {
    id: 'SECRET_AWS_KEY',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'AWS Access Key ID detected',
    pattern: /(?:AKIA|ABIA|ACCA|ASIA)[0-9A-Z]{16}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
    fix: { description: 'Move to environment variables or AWS IAM roles. Rotate the exposed key immediately.' },
  },
  {
    id: 'SECRET_AWS_SECRET',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Possible AWS Secret Access Key',
    pattern: /(?:aws_secret_access_key|AWS_SECRET)\s*[:=]\s*["']?[A-Za-z0-9/+=]{40}["']?/i,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_GITHUB_TOKEN',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'GitHub token detected',
    pattern: /(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{36,}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
    fix: { description: 'Revoke and rotate the token. Use GitHub Actions secrets or environment variables.' },
  },
  {
    id: 'SECRET_STRIPE_KEY',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Stripe API key detected',
    pattern: /(?:sk|pk)_(?:live|test)_[A-Za-z0-9]{20,}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_OPENAI_KEY',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'OpenAI API key detected',
    pattern: /sk-(?:proj-)?[A-Za-z0-9_-]{20,}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_PRIVATE_KEY',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Private key detected',
    pattern: /-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
    fix: { description: 'Never commit private keys. Use a secrets manager or SSH agent.' },
  },
  {
    id: 'SECRET_GENERIC_TOKEN',
    category: 'Secrets',
    severity: Severity.High,
    message: 'Possible hardcoded secret/token',
    pattern: /(?:api_key|apikey|api_secret|secret_key|access_token|auth_token)\s*[:=]\s*["'][A-Za-z0-9+/=_-]{16,}["']/i,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_SLACK_WEBHOOK',
    category: 'Secrets',
    severity: Severity.High,
    message: 'Slack webhook URL detected',
    pattern: /https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9]+\/B[A-Z0-9]+\/[A-Za-z0-9]+/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_GCP_KEY',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Google Cloud API key detected',
    pattern: /AIza[0-9A-Za-z_-]{35}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_AZURE_CONN',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Azure connection string detected',
    pattern: /(?:DefaultEndpointsProtocol|AccountKey)\s*=\s*[A-Za-z0-9+/=]{20,}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_TWILIO',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Twilio API key detected',
    pattern: /SK[a-f0-9]{32}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_SENDGRID',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'SendGrid API key detected',
    pattern: /SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_SQUARE_TOKEN',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Square access token detected',
    pattern: /sq0atp-[A-Za-z0-9_-]{22}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_FIREBASE',
    category: 'Secrets',
    severity: Severity.High,
    message: 'Firebase URL or config with key detected',
    pattern: /(?:firebaseio\.com|firebase\.google\.com)[^\s"']*(?:auth|token|key)\s*[:=]/i,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_MAILGUN',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'Mailgun API key detected',
    pattern: /key-[a-f0-9]{32}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_NPM_TOKEN',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'npm token detected',
    pattern: /\/\/registry\.npmjs\.org\/:_authToken\s*=\s*[A-Za-z0-9_-]+/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_PYPI_TOKEN',
    category: 'Secrets',
    severity: Severity.Critical,
    message: 'PyPI API token detected',
    pattern: /pypi-[A-Za-z0-9_-]{50,}/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
  {
    id: 'SECRET_DOCKER_AUTH',
    category: 'Secrets',
    severity: Severity.High,
    message: 'Docker registry auth detected',
    pattern: /"auth"\s*:\s*"[A-Za-z0-9+/=]{20,}"/,
    cwe: 'CWE-798',
    owasp: 'A07:2021',
  },
];
