import { Rule, Severity } from '../../types.js';

export const sqlInjectionRules: Rule[] = [
  {
    id: 'SQL_CONCAT',
    category: 'SQL Injection',
    severity: Severity.Critical,
    message: 'String concatenation in SQL query — use parameterized queries instead',
    pattern: /(?:SELECT|INSERT|UPDATE|DELETE|DROP|ALTER|CREATE)\s+.*?\+\s*(?:req\.|params\.|query\.|body\.|input|user)/i,
    fileExtensions: ['.ts', '.js', '.py', '.rb', '.java', '.go', '.php'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    fix: { description: 'Use parameterized queries or prepared statements instead of string concatenation' },
  },
  {
    id: 'SQL_TEMPLATE_LITERAL',
    category: 'SQL Injection',
    severity: Severity.Critical,
    message: 'Template literal in SQL query — use parameterized queries instead',
    pattern: /(?:query|execute|exec|raw|prepare)\s*\(\s*`[^`]*\$\{/i,
    fileExtensions: ['.ts', '.js'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    fix: { description: 'Use parameterized queries: db.query("SELECT * FROM x WHERE id = $1", [id])' },
  },
  {
    id: 'SQL_FSTRING',
    category: 'SQL Injection',
    severity: Severity.Critical,
    message: 'f-string in SQL query — use parameterized queries instead',
    pattern: /(?:execute|cursor\.execute|\.query)\s*\(\s*f["'][^"']*\{/i,
    fileExtensions: ['.py'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    fix: { description: 'Use parameterized queries: cursor.execute("SELECT * FROM x WHERE id = %s", (id,))' },
  },
  {
    id: 'SQL_FORMAT',
    category: 'SQL Injection',
    severity: Severity.High,
    message: 'String format in SQL query — use parameterized queries instead',
    pattern: /(?:execute|query)\s*\(\s*["'].*?(?:SELECT|INSERT|UPDATE|DELETE).*?["']\s*[%\.]\s*format/i,
    fileExtensions: ['.py'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    fix: { description: 'Use parameterized queries instead of .format()' },
  },
  {
    id: 'SQL_RAW_QUERY',
    category: 'SQL Injection',
    severity: Severity.Medium,
    message: 'Raw SQL query detected — ensure inputs are sanitized',
    pattern: /\.(?:rawQuery|raw|unsafe|unsafeRaw)\s*\(/i,
    cwe: 'CWE-89',
    owasp: 'A03:2021',
  },
  {
    id: 'SQL_SPRINTF',
    category: 'SQL Injection',
    severity: Severity.Critical,
    message: 'sprintf/Sprintf in SQL query — use parameterized queries',
    pattern: /(?:Sprintf|sprintf)\s*\(\s*["'](?:SELECT|INSERT|UPDATE|DELETE|DROP)/i,
    fileExtensions: ['.go', '.php'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    fix: { description: 'Use parameterized queries with ? or $1 placeholders' },
  },
  {
    id: 'SQL_STRING_CONCAT_JAVA',
    category: 'SQL Injection',
    severity: Severity.Critical,
    message: 'String concatenation in Java SQL — use PreparedStatement',
    pattern: /(?:executeQuery|executeUpdate|execute)\s*\(\s*["']?\s*(?:SELECT|INSERT|UPDATE|DELETE).*?\+/i,
    fileExtensions: ['.java'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    fix: { description: 'Use PreparedStatement with ? parameters' },
  },
  {
    id: 'SQL_PHP_VARIABLE',
    category: 'SQL Injection',
    severity: Severity.Critical,
    message: 'PHP variable interpolation in SQL — use prepared statements',
    pattern: /(?:query|exec|execute)\s*\(\s*["'](?:SELECT|INSERT|UPDATE|DELETE)[^"']*\$(?:_GET|_POST|_REQUEST|\w+)/i,
    fileExtensions: ['.php'],
    cwe: 'CWE-89',
    owasp: 'A03:2021',
    fix: { description: 'Use PDO prepared statements with bindParam()' },
  },
];
