import { Rule, Severity } from '../../types.js';

export const xssRules: Rule[] = [
  {
    id: 'XSS_INNERHTML',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'innerHTML assignment — use textContent or sanitize input',
    pattern: /\.innerHTML\s*[=+](?!=)/,
    fileExtensions: ['.ts', '.js', '.jsx', '.tsx', '.vue'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
    fix: { description: 'Use element.textContent = value instead, or sanitize with DOMPurify' },
  },
  {
    id: 'XSS_DOCUMENT_WRITE',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'document.write() is an XSS sink — avoid using it',
    pattern: /document\.write(?:ln)?\s*\(/,
    fileExtensions: ['.ts', '.js', '.jsx', '.tsx', '.html'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
    fix: { description: 'Use DOM APIs (createElement, textContent) instead of document.write' },
  },
  {
    id: 'XSS_REACT_DANGEROUS',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'dangerouslySetInnerHTML — ensure content is sanitized',
    pattern: /dangerouslySetInnerHTML/,
    fileExtensions: ['.tsx', '.jsx', '.js', '.ts'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
    fix: { description: 'Sanitize HTML with DOMPurify before passing to dangerouslySetInnerHTML' },
  },
  {
    id: 'XSS_VUE_VHTML',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'v-html directive — ensure content is sanitized',
    pattern: /v-html\s*=/,
    fileExtensions: ['.vue'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
  },
  {
    id: 'XSS_ANGULAR_BYPASS',
    category: 'Cross-Site Scripting',
    severity: Severity.Critical,
    message: 'Angular security bypass — review carefully',
    pattern: /bypassSecurityTrust(?:Html|Script|Style|Url|ResourceUrl)/,
    fileExtensions: ['.ts', '.js'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
  },
  {
    id: 'XSS_OUTERHTML',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'outerHTML assignment — potential XSS vector',
    pattern: /\.outerHTML\s*[=+](?!=)/,
    fileExtensions: ['.ts', '.js', '.jsx', '.tsx'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
  },
  {
    id: 'XSS_INSERT_ADJACENT',
    category: 'Cross-Site Scripting',
    severity: Severity.Medium,
    message: 'insertAdjacentHTML — ensure content is sanitized',
    pattern: /\.insertAdjacentHTML\s*\(/,
    fileExtensions: ['.ts', '.js', '.jsx', '.tsx'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
  },
  {
    id: 'XSS_JQUERY_HTML',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'jQuery .html() with dynamic content — potential XSS',
    pattern: /\$\s*\([^)]+\)\s*\.html\s*\(\s*[^"')\s]/,
    fileExtensions: ['.js', '.ts'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
    fix: { description: 'Use .text() for plain text or sanitize HTML before .html()' },
  },
  {
    id: 'XSS_LOCATION_HREF',
    category: 'Cross-Site Scripting',
    severity: Severity.Medium,
    message: 'Unvalidated URL assignment to location — potential XSS via javascript: URLs',
    pattern: /(?:location|window\.location)\s*(?:\.href)?\s*=\s*(?:req\.|params\.|query\.|body\.|input|user|data)/i,
    fileExtensions: ['.ts', '.js', '.jsx', '.tsx'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
  },
  {
    id: 'XSS_JINJA_UNESCAPED',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'Jinja2 unescaped output — use {{ var }} instead of {{ var|safe }}',
    pattern: /\{\{.*\|\s*safe\s*\}\}/,
    fileExtensions: ['.html', '.jinja', '.j2'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
  },
  {
    id: 'XSS_ERB_RAW',
    category: 'Cross-Site Scripting',
    severity: Severity.High,
    message: 'ERB raw/html_safe output — ensure content is sanitized',
    pattern: /<%=\s*raw\s|\.html_safe/,
    fileExtensions: ['.erb', '.rb'],
    cwe: 'CWE-79',
    owasp: 'A03:2021',
  },
];
